[tool.poetry]
name = "multicommand"
version = "0.0.1"
description = "Create simple nested argparse CLIs"
authors = ["Andrew Ross <andrew.ross.mail@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6.1"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.9.0"
pylint = "^2.7.4"
reorder-python-imports = "^2.4.0"
bump2version = "^1.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
